# Generated by Django 3.2.16 on 2024-03-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20240327_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='after_pics',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='before_pics',
            field=models.ImageField(upload_to=''),
        ),
    ]
